---
title: "project 2"
author: "zhiwei xiao"
date: "6/19/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning = FALSE, message = FALSE}
library(tidyverse)
library(forcats)
library(glmnet)
library(ggcorrplot)
library(boot)
library(leaps)

owl_data <- read_csv("http://www.stat.cmu.edu/cmsac/sure/materials/data/regression_projects/overwatch_odds.csv")

colnames(owl_data)
```

```{r}
new_owl_data <- owl_data %>% 
                mutate(winner_label = ifelse(winner_label == 0, "team_one", "team_two"),
                       corona_virus_isolation = ifelse(corona_virus_isolation == TRUE, "isolation", "no isolation")) %>%
                select(-c("X1", "id", "date", "stage","t1_odds","t1_probability","t1_place_last_season", 
                          "t2_place_last_season","t1_wins_season", "t1_losses_season", "t2_wins_season",
                          "t2_losses_season","t1_matches_season", "t2_matches_season", "t1_matches_alltime", 
                          "t1_losses_alltime", "t2_matches_alltime", "t2_losses_alltime", "t1_losses_vs_t2", 
                          "t1_matches_vs_t2")) %>% 
                na.omit()

table(new_owl_data$corona_virus_isolation)
dim(new_owl_data)

## winner geom_bar graph
new_owl_data %>% ggplot(aes(fct_infreq(winner), 
                             fill = corona_virus_isolation)) + 
                  geom_bar() + 
                  coord_flip()  + 
                  theme_bw() + xlab("team name") + ylab("winning count") + 
                  ggtitle("winning count for each team before and after coronavirus isolation") +
                  scale_fill_manual("legend", values = c("isolation" = "springgreen", "no isolation" = "hotpink"))

## the more negative the odds are, the larger probability that this team would win.

cor(new_owl_data$t2_odds, new_owl_data$t2_probability)
ggplot(data = new_owl_data, aes(x = t2_odds, y = t2_probability)) + 
  geom_point(size = 1, color = "red") + 
  geom_smooth(method = "loess") +
  theme_bw() + 
  annotate("text", x=-4000, y=45, label= "correlation: -0.816545", color = "royalblue", size = 5)

```



```{r}
## correlation matrix

colnames(new_owl_data)

## ignore t1_odds, t1_probability, t2_probability because they're very correlated with t2_odds
owl_model_data <- new_owl_data %>% select(t1_win_percent_season, t2_win_percent_season, t1_win_percent_alltime, t2_win_percent_alltime,
                                          t1_win_percent_last_5, t2_win_percent_last_5, t1_win_percent_vs_t2, t1_win_percent_last_10, 
                                          t2_win_percent_last_10, t1_win_percent_last_20, t2_win_percent_last_20, t1_wins_vs_t2, t2_odds)

## scaling the data
owl_mean <- colMeans(owl_model_data)
owl_std <- sqrt(diag(var(owl_model_data)))
owl_model_data <- scale(owl_model_data, center = owl_mean, scale = owl_std)
owl_model_data <- as_tibble(owl_model_data)

round_cor_matrix <- round(cor(owl_model_data), 2)
ggcorrplot(round_cor_matrix, 
           hc.order = TRUE,
           type = "lower",
           lab = TRUE, tl.cex = 9, lab_size = 3)

```


```{r}
## variables selection

regfit.full <- regsubsets(t2_odds ~ ., data = owl_model_data, nvmax = ncol(owl_model_data) - 1)
regfit.summary <- summary(regfit.full)
regfit.summary
```


```{r}
par(mfrow = c(2,2))

plot(regfit.summary$adjr2, type = "l", ylab = "Adjusted RSq", main = "Adjusted RSq", xlab = "Number of Variables")
best_adjr2 <- which.max(regfit.summary$adjr2)
abline(v = best_adjr2, lty = 2, col = "red")

plot(regfit.summary$rss, type = "l", ylab = "RSS", main = "RSS", xlab = "Number of Variables")

plot(regfit.summary$bic, type = "l", ylab = "BIC", main = "BIC", xlab = "Number of Variables")
best_bic <- which.min(regfit.summary$bic)
abline(v = best_bic, lty = 2, col = "red")

plot(regfit.summary$cp, type = "l", ylab = "Cp", main = "Mallows Cp", xlab = "Number of Variables")
best_cp <- which.min(regfit.summary$cp)
abline(v = best_cp, lty = 2, col = "red")
```




```{r}
### 10-fold cross validation for three candidate models chosen by the variable selections

set.seed(200)

model1 <- glm(t2_odds ~ t1_win_percent_season + t2_win_percent_season + t1_win_percent_last_5 + 
              t2_win_percent_last_5 + t1_win_percent_last_20, data = owl_model_data)
model1_cv_error <- cv.glm(owl_model_data, model1, K = 10)$delta[1]
model1_cv_error


model2 <- glm(t2_odds ~ t1_win_percent_season + t2_win_percent_season + t1_win_percent_last_5 + t2_win_percent_last_5 + 
              t1_win_percent_last_20 + t2_win_percent_last_10, data = owl_model_data)
model2_cv_error <- cv.glm(owl_model_data, model2, K = 10)$delta[1]
model2_cv_error


model3 <- glm(t2_odds ~ t1_win_percent_season + t2_win_percent_season + t1_win_percent_last_5 + t2_win_percent_last_5 + 
              t1_win_percent_last_20 + t2_win_percent_last_10 + t2_win_percent_last_20, data = owl_model_data)
model3_cv_error <- cv.glm(owl_model_data, model3, K = 10)$delta[1]
model3_cv_error


full_model <- glm(t2_odds ~ ., data = owl_model_data)
full_cv_error <- cv.glm(owl_model_data, full_model, K = 10)$delta[1]
full_cv_error
```

```{r}
summary(model2)
plot(model2$residuals ~ model2$fitted.values, main = "Final Model Residual Plot", xlab = "Fitted Values", ylab = "Residuals")
abline(a = 0, b = 0, col = "gray60")
```


```{r}
par(mfrow = c(2,2))
set.seed(200)
X <- model.matrix(t2_odds ~ ., owl_model_data)
y <- owl_model_data$t2_odds


### ridge regression
ridge.mod <- glmnet(X, y, alpha = 0)
plot(ridge.mod, xvar = "lambda", label = TRUE)

## best ridge regression model based on cross validation
cv.out <- cv.glmnet(X, y, alpha = 0)
plot(cv.out)
bestlam <- cv.out$lambda.min
lambda.grid <- cv.out$lambda
mses <- cv.out$cvm
cv_error <- mses[which(lambda.grid == bestlam)]
cv_error




### lasso regression
lasso.mod <- glmnet(X, y, alpha = 1)
plot(lasso.mod, xvar = "lambda", label = TRUE)

### best lasso regression model based on cross validation
lasso.cv.out <- cv.glmnet(X, y, alpha = 1)
plot(lasso.cv.out)
lasso.bestlam <- lasso.cv.out$lambda.min
lasso.lambda.grid <- lasso.cv.out$lambda
lasso.mses <- lasso.cv.out$cvm
lasso.cv_error <- lasso.mses[which(lasso.lambda.grid == lasso.bestlam)]
lasso.cv_error
```










